[character]
success_symbol = "[ğŸŠ](bold green) "
error_symbol = "[ğŸ‹](bold red) "

[cmd_duration]
# disabled = false
min_time = 0

[git_branch]
symbol = "ğŸŒ± "
# truncation_length = 4
# truncation_symbol = ""

[git_status]
disabled = true